import { age, callback, empty, toggle, username } from "./basic/1";
import { person } from "./basic/2";
import { action, element } from "./basic/3";
import { calc, showMessage } from "./basic/4";
import { DayOfWeek, isWeekend } from "./basic/5";
import { mango, poly } from "./basic/6";
import { page1, page2 } from "./basic/7";
import { merged } from "./generics/3";
import { RoleDescription } from "./generics/5";
import { formParams } from "./generics/6";
import "./style.css";

console.log(age);
console.log(username);
console.log(toggle);
console.log(empty);
console.log(callback);
console.log(person);
console.log(element);
console.log(action);
showMessage("hello world");
console.log(calc(10, 10));
console.log(isWeekend(DayOfWeek.Monday));
console.log(mango);
console.log(poly);
console.log(page1);
console.log(page2);
console.log(merged.name);
console.log(formParams);
console.log(RoleDescription.admin);
